/* do not change this file, it is auto generated by storybook. */
import { start, updateView, type View } from "@storybook/react-native";

import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "./.rnstorybook/stories",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    // @ts-expect-error
    req: require.context(
      "./stories",
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  },
];

declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
}

const annotations = [
  require("./preview"),
  require("@storybook/react-native/preview"),
];

global.STORIES = normalizedStories;

// @ts-expect-error
module?.hot?.accept?.();

if (global.view) {
  updateView(global.view, annotations, normalizedStories);
} else {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
}

export const view: View = global.view;
